#!/usr/bin/env python

import requests
import json
import yaml
import re
import sys

with open("config.yaml", "r") as ymlfile:
    harness_config = yaml.load(ymlfile, Loader=yaml.FullLoader)

config = harness_config["canary"]
canary_hostname = config["opsani_app_name"]

with open("/run/secrets/optune_newrelic_apm_app_id", "r") as auth_file:
    newrelic_app_id = auth_file.read().strip()

with open("/run/secrets/optune_newrelic_apm_api_key", "r") as auth_file:
    newrelic_api_key = auth_file.read().strip()

url = f"https://api.newrelic.com/v2/applications/{newrelic_app_id}/instances.json"
headers = {
    "X-Api-Key": newrelic_api_key
}

result = requests.post(url,headers=headers).json()

monitoring = {'instance_ids': [], 'ref_instance_ids': []}
for item in result['application_instances']:
    if canary_hostname in item['host']:
        monitoring['instance_ids'].append(item['host'])
    else:
        monitoring['ref_instance_ids'].append(item['host'])
 
print(json.dumps(monitoring), file=sys.stdout)
